---
# Ejercicios extra

### Notebook de Noe 👻👻

### Resolucion de ejercicios de la web: https://www.machinelearningplus.com/python/101-numpy-exercises-python/

---

---
### 1. Import numpy as np and see the version

---

In [1]:
import numpy as np

print(np.__version__)


1.23.3


---

## 2. How to create a 1D array?

Desired output --> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

---

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

---
## How to create a boolean array?

Q. Create a 3×3 numpy array of all True’s

---

In [5]:
arr2 = np.ones((3,3),dtype=bool)
arr2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

---
# 4. How to extract items that satisfy a given condition from 1D array?

Q. Extract all odd numbers from arr


```python
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Desired output: 
> array([1, 3, 5, 7, 9])

```
---

In [6]:
arr = np.arange(10)

mask = arr%2!=0
print(arr)
print(arr[mask])

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


---
# 5. How to replace items that satisfy a condition with another value in numpy array?

Q. Replace all odd numbers in arr with -1

---

In [7]:
arr = np.arange(10)
mask = arr%2!=0
print(arr)


arr[mask]=-1
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


---
# 6. How to replace items that satisfy a condition without affecting the original array?

Q. Replace all odd numbers in arr with -1 without changing arr

---

In [8]:
arr = np.arange(10)
mask = arr%2!=0

arr2 = arr.copy()
arr2[mask]=-1

print(arr)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


---
# 7. How to reshape an array?

Q. Convert a 1D array to a 2D array with 2 rows

---

In [11]:
arr = np.arange(10)
print(arr)


arr = arr.reshape(2,-1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


---
# 8. How to stack two arrays vertically?

Q. Stack arrays a and b vertically

```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```
---

In [14]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

c = np.vstack((a,b))

print("a --> \n", a)
print("b --> \n", b)
print("c --> \n", c)

a --> 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
b --> 
 [[1 1 1 1 1]
 [1 1 1 1 1]]
c --> 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


---
# 9. How to stack two arrays horizontally?

Q. Stack the arrays a and b horizontally.

```
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
```

---

In [15]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

c = np.hstack((a,b))

print("a --> \n", a)
print("b --> \n", b)
print("c --> \n", c)

a --> 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
b --> 
 [[1 1 1 1 1]
 [1 1 1 1 1]]
c --> 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


---
# 10. How to generate custom sequences in numpy without hardcoding?

Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

```
a = np.array([1,2,3])

# Desired output
array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```
---

In [18]:
a = np.array([1,2,3])
b = np.repeat(a,3)
c = np.tile(a,3)
print("resultado parcial --> ", b)
print("resultado parcial --> ", c)

d = np.concatenate((b,c))
print("resultado final --> ", d)

resultado parcial -->  [1 1 1 2 2 2 3 3 3]
resultado parcial -->  [1 2 3 1 2 3 1 2 3]
resultado final -->  [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


---
# 11. How to get the common items between two python numpy arrays?

Q. Get the common items between a and b

```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Desired Output:

array([2, 4])
```
---

In [19]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c = np.intersect1d(a,b)
print(c)

[2 4]


---
# 12. How to remove from one array those items that exist in another?

Q. From array a remove all items present in array b

```
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# Desired output
array([1,2,3,4])

```

---

In [21]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c = np.intersect1d(a,b)

mask = np.where(a!=c)
print(a[mask])

[1 2 3 4]


In [22]:
# another form
print(np.setdiff1d(a,b))

[1 2 3 4]


---
# 13. How to get the positions where elements of two arrays match?

Q. Get the positions where elements of a and b match

```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Desired output
array([1, 3, 5, 7])

```
---

In [23]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c = np.where(a==b)

print("match positions --> ",c)

match positions -->  (array([1, 3, 5, 7], dtype=int64),)


---
# 14. How to extract all numbers between a given range from a numpy array?

Q. Get all items between 5 and 10 from a.

```
a = np.array([2, 6, 1, 9, 10, 3, 27])
```
---

In [25]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

mask = (a>=5) & (a<=10)

print("Items between 5 and 10 --> ", a[mask])

Items between 5 and 10 -->  [ 6  9 10]


---
# 15. How to make a python function that handles scalars to work on numpy arrays?

Q. Convert the function maxx that works on two scalars, to work on two arrays.

```
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5) # salida 5

# Desired output

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
# > array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

```



---

In [31]:
# Work with numbers
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

# Work with numpy arrays

def maxx_np(x, y):
    """Get the maximum of two arrays"""
    return np.max((x,y), axis=0)

In [32]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

maxx_np(a,b)

array([6, 7, 9, 8, 9, 7, 5])

---
# 16. How to swap two columns in a 2d numpy array?

Q. Swap columns 1 and 2 in the array arr.

```
arr = np.arange(9).reshape(3,3)
```
---

In [37]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr = arr[:,[1,0,2]]
print(arr) 


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


---
# 17. How to swap two rows in a 2d numpy array?

Q. Swap rows 1 and 2 in the array arr

---

In [38]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr = arr[[1,0,2]]
print(arr) 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


---
# 18. How to reverse the rows of a 2D array?

---

In [41]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr = arr[::-1]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


---
# 19. How to reverse the columns of a 2D array?

---

In [42]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr = arr[:, ::-1]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


---
# 20. How to create a 2D array containing random floats between 5 and 10?

Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

---

In [44]:
arr = np.random.uniform(5,10, size=(5,3))
print(arr)

[[8.91881065 7.10551068 8.96167805]
 [8.69112858 8.43228957 9.41425129]
 [9.27771162 9.35351397 9.68217363]
 [5.11435064 8.3485836  5.38320346]
 [5.83076863 5.18171772 6.07424622]]


---
# 21. How to print only 3 decimal places in python numpy array?

Q. Print or show only 3 decimal places of the previous np array

---

In [45]:
arr = np.random.uniform(5,10, size=(5,3))
np.set_printoptions(precision=3)

arr

array([[7.361, 9.085, 5.532],
       [5.471, 6.067, 9.269],
       [6.893, 9.602, 6.198],
       [9.401, 5.19 , 7.074],
       [9.148, 6.954, 7.781]])

---
# 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

```
# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

#> array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
#>        [  8.447761e-04,   4.718856e-06,   1.215691e-04],
#>        [  6.707491e-04,   8.258528e-04,   1.367066e-04]])

# Desired Output
#> array([[ 0.000543,  0.000278,  0.000425],
#>        [ 0.000845,  0.000005,  0.000122],
#>        [ 0.000671,  0.000826,  0.000137]])

```
---

In [46]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [49]:
np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

---
# 23. How to limit the number of items printed in output of numpy array?

Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.

```
a = np.arange(15)
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Desired output
#> array([ 0,  1,  2, ..., 12, 13, 14])

```
---

In [50]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [51]:
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

---
# 24. How to print the full numpy array without truncating

Q. Print the full numpy array a without truncating

```
np.set_printoptions(threshold=6)
a = np.arange(15)
a
#> array([ 0,  1,  2, ..., 12, 13, 14])

# desired output
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
```

---

In [52]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [57]:
np.set_printoptions(threshold=10000)
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

---
# 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?

Q. Import the iris dataset keeping the text intact.

---

In [58]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# print first 5 rows
iris[:5]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa']], dtype=object)

---
# 26. How to extract a particular column from 1D array of tuples?

Q. Extract the text column species from the 1D iris imported in previous question.

```
# input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```` 

---

In [60]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

species = iris[:,4]
print(species)

[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-versicolor' b'Iris-versicolor'
 b'Iris-versicolor' b'Iris-versicolor' b'Iris-versicolor'
 b'Iris-versicolor' b'Iris-versicolor' b'Iris-versicolor'
 b'Iris-versicolor' b'Iris-versicolor' b'Iris-versicolor'
 b'Iris-versicolor' b'Iri

---
# 27. How to convert a 1d array of tuples to a 2d numpy array?

Q. Convert the 1D iris to 2D array iris_2d by omitting the species text field.

```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

```
---

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

---
# 28. How to compute the mean, median, standard deviation of a numpy array?

Q. Find the mean, median, standard deviation of iris's sepallength (1st column)

---

In [62]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

my_mean = np.mean(sepallength)
my_median = np.median(sepallength)
my_std = np.std(sepallength)

print("mean --> ", my_mean)
print("median --> ", my_median)
print("std --> ", my_std)

mean -->  5.843333333333334
median -->  5.8
std -->  0.8253012917851409


---
# 29. How to normalize an array so the values range exactly between 0 and 1?

---

In [64]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

sl_max = np.max(sepallength)
sl_min = np.min(sepallength)


sl_norm = (sepallength - sl_min)/(sl_max - sl_min)

sl_norm

array([0.222222, 0.166667, 0.111111, 0.083333, 0.194444, 0.305556,
       0.083333, 0.194444, 0.027778, 0.166667, 0.305556, 0.138889,
       0.138889, 0.      , 0.416667, 0.388889, 0.305556, 0.222222,
       0.388889, 0.222222, 0.305556, 0.222222, 0.083333, 0.222222,
       0.138889, 0.194444, 0.194444, 0.25    , 0.25    , 0.111111,
       0.138889, 0.305556, 0.25    , 0.333333, 0.166667, 0.194444,
       0.333333, 0.166667, 0.027778, 0.222222, 0.194444, 0.055556,
       0.027778, 0.194444, 0.222222, 0.138889, 0.222222, 0.083333,
       0.277778, 0.194444, 0.75    , 0.583333, 0.722222, 0.333333,
       0.611111, 0.388889, 0.555556, 0.166667, 0.638889, 0.25    ,
       0.194444, 0.444444, 0.472222, 0.5     , 0.361111, 0.666667,
       0.361111, 0.416667, 0.527778, 0.361111, 0.444444, 0.5     ,
       0.555556, 0.5     , 0.583333, 0.638889, 0.694444, 0.666667,
       0.472222, 0.388889, 0.333333, 0.333333, 0.416667, 0.472222,
       0.305556, 0.472222, 0.666667, 0.555556, 0.361111, 0.333

---
# 30. How to compute the softmax score?

---

In [66]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

def softmax(arr):
    expo = np.exp(arr - arr.max())
    sum_expo = expo.sum()

    answ = expo/sum_expo
    return answ

softmax(sepallength)


array([0.00222 , 0.001817, 0.001488, 0.001346, 0.002008, 0.002996,
       0.001346, 0.002008, 0.001102, 0.001817, 0.002996, 0.001644,
       0.001644, 0.000997, 0.00447 , 0.004044, 0.002996, 0.00222 ,
       0.004044, 0.00222 , 0.002996, 0.00222 , 0.001346, 0.00222 ,
       0.001644, 0.002008, 0.002008, 0.002453, 0.002453, 0.001488,
       0.001644, 0.002996, 0.002453, 0.003311, 0.001817, 0.002008,
       0.003311, 0.001817, 0.001102, 0.00222 , 0.002008, 0.001218,
       0.001102, 0.002008, 0.00222 , 0.001644, 0.00222 , 0.001346,
       0.002711, 0.002008, 0.01484 , 0.008144, 0.013428, 0.003311,
       0.009001, 0.004044, 0.007369, 0.001817, 0.009947, 0.002453,
       0.002008, 0.00494 , 0.005459, 0.006033, 0.003659, 0.010994,
       0.003659, 0.00447 , 0.006668, 0.003659, 0.00494 , 0.006033,
       0.007369, 0.006033, 0.008144, 0.009947, 0.01215 , 0.010994,
       0.005459, 0.004044, 0.003311, 0.003311, 0.00447 , 0.005459,
       0.002996, 0.005459, 0.010994, 0.007369, 0.003659, 0.003

---
# 31. How to find the percentile scores of a numpy array?
---

In [69]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

Q1 = np.percentile(sepallength,25)
Q2 = np.percentile(sepallength, 50)
Q3 = np.percentile(sepallength,75)

print("Q1 --> ", Q1)
print("Q2 --> ", Q2)
print("Q3 --> ", Q3)

print("Median (must be equal to Q2)--> ", np.median(sepallength))

Q1 -->  5.1
Q2 -->  5.8
Q3 -->  6.4
Median (must be equal to Q2)-->  5.8


---
# 32. How to insert values at random positions in an array?

Q. Insert np.nan values at 20 random positions in iris_2d dataset

---

In [70]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
i, j = np.where(iris_2d)

x = np.random.choice((i), 20) 
y = np.random.choice((j), 20) 

iris_2d[x,y]=np.nan
print(iris_2d)

[[b'5.1' b'3.5' nan b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' nan b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' b'1.5' b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' nan b'Iris-setosa']
 [b'5.7' b'3.8' b'1.7' nan b'Iris-setosa']
 [b'5.1' b'3.8' b'1.5' b'0.3' b'Iris-setosa']
 [b'5.4' b'3.4' b'1.7' b'0.2' b'Iris-setosa']
 [b'5.1' b'3.7' b'1.5' b'0.4' b'Iris-setosa']


---
# 33. How to find the position of missing values in numpy array?
Q. Find the number and position of missing values in iris_2d's sepallength (1st column)

```
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
```

---

In [2]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [7]:
# number of nan in col 0
nan_idx = np.argwhere(np.isnan(iris_2d[:,0]))
print(nan_idx)
print("number of nan in col 0--> ", np.isnan(iris_2d[:,0]).sum())


[[12]
 [19]
 [40]
 [60]]
number of nan in col 0-->  4


---
# 34. How to filter a numpy array based on two or more conditions?

Q. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

---

In [9]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')

mask = (iris_2d[:,2]>1.5) & (iris_2d[:,0]<5)

iris_2d[mask]

array([[4.8, 3.4, 1.6, 0.2, nan],
       [4.8, 3.4, 1.9, 0.2, nan],
       [4.7, 3.2, 1.6, 0.2, nan],
       [4.8, 3.1, 1.6, 0.2, nan],
       [4.9, 2.4, 3.3, 1. , nan],
       [4.9, 2.5, 4.5, 1.7, nan]])

---
# 35. How to drop rows that contain a missing value from a numpy array?

Q. Select the rows of iris_2d that does not have any nan value.

---

In [24]:
# Input
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
# iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
arr = np.arange(50, dtype=float).reshape(5,-1)

arr[1,3] = np.nan
arr[2,1] = np.nan
arr[1,1] = np.nan
arr[0,3] = np.nan

print(arr)


[[ 0.  1.  2. nan  4.  5.  6.  7.  8.  9.]
 [10. nan 12. nan 14. 15. 16. 17. 18. 19.]
 [20. nan 22. 23. 24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]]


In [35]:
# we must drop 2nd and 4th column

mask = (np.isnan(arr).sum(axis=0)==0)
print("arr --> \n",arr)
print("\narr clean --> \n", arr[:,mask])

arr --> 
 [[ 0.  1.  2. nan  4.  5.  6.  7.  8.  9.]
 [10. nan 12. nan 14. 15. 16. 17. 18. 19.]
 [20. nan 22. 23. 24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]]

arr clean --> 
 [[ 0.  2.  4.  5.  6.  7.  8.  9.]
 [10. 12. 14. 15. 16. 17. 18. 19.]
 [20. 22. 24. 25. 26. 27. 28. 29.]
 [30. 32. 34. 35. 36. 37. 38. 39.]
 [40. 42. 44. 45. 46. 47. 48. 49.]]


---
# 36. How to find the correlation between two columns of a numpy array?

```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

```

---

In [40]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

col0=iris_2d[:,0]
col1=iris_2d[:,1]
col2=iris_2d[:,2]

corr = np.corrcoef(col0,col1)
print("correlation matrix --> \n",corr)



correlation matrix --> 
 [[ 1.         -0.10936925]
 [-0.10936925  1.        ]]


---
# 37. How to find if a given array has any null values?

Q. Find out if iris_2d has any missing values.

---

In [44]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


if np.isnan(iris_2d).any():
    print("There is null values")
else:
    print("There is not null values")

False

---
# 38. How to replace all missing values with 0 in a numpy array?

Q. Replace all ccurrences of nan with 0 in numpy array

---

In [48]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

mask = np.isnan(iris_2d)

iris_2d[mask] = 0
iris_2d[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [0. , 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 0. , 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

---
# 39. How to find the count of unique values in a numpy array?

Q. Find the unique values and the count of unique values in iris's species

---

In [50]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

species = iris[:,4]

uniques_species, number_unique = np.unique(especies,return_counts=True)

print("Uniques species --> ", uniques_species)
print("Count of unique species --> ", number_unique)


Uniques species -->  [b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica']
Count of unique species -->  [50 50 50]


---
# 40. How to convert a numeric to a categorical (text) array?

Q. Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:

* Less than 3 --> 'small'
* 3-5 --> 'medium'
* '>=5 --> 'large'
---

In [58]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


iris_sl = iris[:,2]

mask1 = iris_sl < 3
mask2 = (iris_sl < 5) & (iris_sl>= 3)
mask3 = iris_sl >= 5

iris_sl[mask1]= 0
iris_sl[mask2] = 1
iris_sl[mask3] = 2

dictionary = {
    0.0: "small",
    1.0: "medium",
    2.0: "large"
}


iris_sl_cat = [dictionary[x] for x in iris_sl]
iris_sl_cat



['small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'large',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'large',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'mediu

---
# 41. How to create a new column from existing columns of a numpy array?

---